### PR TITLE
Updated the headings of each method excluding the methods displaying …

### PR DESCRIPTION
**Pull request by Desiree98**
…the totals.

### CODE REVIEW

**Review by Calixte-Williams — COMMENTED** [review]
You still have it printing abbreviations, like Top N Countries, etc.
Remove the abbreviations.

**Comment by Desiree98** [comment]
Changes have been made.

**Review by Calixte-Williams — CHANGES_REQUESTED** [review]
Make report Titles more human readable.

**Review by Calixte-Williams — APPROVED** [review]
Titles are fine

**Review by Jermon1 — APPROVED** [review]

**Pull request merged**
